import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@fontsource/inter';
import {CssVarsProvider} from '@mui/joy/styles';
import theme from "@/app/theme";
import ColorInit from "@/app/colorinit";

const inter = Inter({subsets: ['latin']})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
//theme from joy UI

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <ColorInit/>
        {/*Joy UI theme*/}
        <CssVarsProvider theme={theme} defaultMode="system">
            {children}
        </CssVarsProvider>
        </body>
        </html>
    )
}
