import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fontsource/inter';
import { CssVarsProvider } from '@mui/joy/styles';
import theme from "@/app/_config/theme";
import ColorInit from "@/app/_config/colorinit";
import React from "react";
import { ReduxProvider } from './_store/provider';

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
//theme from joy UI

export default function RootLayout({ children, }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <ColorInit />
                {/*Joy UI theme*/}
                <ReduxProvider>
                    <CssVarsProvider theme={theme} defaultMode="system">
                        {children}
                    </CssVarsProvider>
                </ReduxProvider>
            </body>
        </html>
    )
}
